// Project Package.cpp — UPackage implementations.

#include "Game/Object/Package.h"
#include "Game/System/GC/GCSystem.h"

namespace Maho
{

UPackage::UPackage(std::string InName, EPackageFlags InFlags)
	: UObject(nullptr, std::move(InName))
	, PackageFlags(InFlags)
{
}

UPackage::~UPackage()
{
	OnPoolTearDown();
}

void UPackage::OnPoolTearDown()
{
	Objects.clear();
	FilePath.clear();
}

FObjectRef UPackage::FindObject(const std::string& InObjectName) const
{
	const auto It = Objects.find(InObjectName);
	if (It == Objects.end())
	{
		return FObjectRef();
	}
	return FObjectRef::Wrap(It->second);
}

bool UPackage::IsPersistent() const
{
	return ::Maho::HasAnyPackageFlags(PackageFlags, EPackageFlags::Persistent);
}

bool UPackage::IsTransient() const
{
	return ::Maho::HasAnyPackageFlags(PackageFlags, EPackageFlags::Transient);
}

bool UPackage::RegisterObject(UObject* Object)
{
	if (!Object || Object->GetName().empty())
	{
		return false;
	}
	const auto& Name = Object->GetName();
	if (Objects.find(Name) != Objects.end())
	{
		return false;
	}
	Objects.emplace(Name, Object);
	return true;
}

void UPackage::DetachObject(UObject* Object)
{
	if (!Object)
	{
		return;
	}
	const auto& Name = Object->GetName();
	Objects.erase(Name);
}

} // namespace Maho

// ── UPackage reflection (normally generated by codegen) ──

// Forward-declared; defined in the generated ObjectReflectTypes.gen.cpp
// Stub that returns UObject's type until proper codegen integration.

namespace Maho
{

const FObjectType& UPackage::StaticType()
{
	static const FObjectType Type =
	{
		"Maho::UPackage",
		&UObject::StaticType(),
		nullptr,
		0,
		nullptr,
		0,
	};
	return Type;
}

const FObjectType& UPackage::GetObjectType() const
{
	return StaticType();
}

} // namespace Maho
